### ISSUE TITLE
Feeding vJoy device number 0 failed - try to enable device then press enter

### ISSUE THREAD

**Issue by JOniCreezeX** [mfosse/JoyCon-Driver#57] opened 2018-01-21 07:50 UTC
Every time I try to connect joycons
Feeding vJoy device number 0 failed - try to enable device then press enter
I press enter - 
battery level : (vary)
battery level : 0

Settings : combine joycons : false
Gyro : true
Gyro window : true

**Comment by mfosse** [comment] 2018-01-23 14:16
Did you enable vJoy?

**Comment by mfosse** [comment] 2018-01-23 15:06
This is a duplicate of issue #49 and it should be fixed in the latest release.

**Closed by mfosse** 2018-01-23 15:06 UTC
